# Generated by Django 2.1.4 on 2020-01-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='商品spu名称', max_length=20, verbose_name='商品spu名称')),
                ('detail', models.TextField(help_text='商品详情', verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品spu',
                'verbose_name_plural': '商品spu',
                'db_table': 'db_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('image', models.URLField(help_text='商品图片', verbose_name='商品图片')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'db_goods_image',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='商品名称', max_length=30, verbose_name='商品名称')),
                ('desc', models.TextField(help_text='商品简介', verbose_name='商品简介')),
                ('price', models.FloatField(help_text='商品价格', verbose_name='商品价格')),
                ('unite', models.CharField(help_text='商品单位', max_length=20, verbose_name='商品单位')),
                ('image', models.URLField(help_text='商品图片', verbose_name='商品图片')),
                ('stock', models.IntegerField(help_text='商品库存', verbose_name='商品库存')),
                ('sales', models.IntegerField(help_text='商品销量', verbose_name='商品销量')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, help_text='商品状态', verbose_name='商品状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品spu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='商品种类', max_length=30, verbose_name='商品种类')),
                ('logo', models.CharField(help_text='商品种类logo', max_length=20, verbose_name='商品种类logo')),
                ('image', models.URLField(help_text='种类图片', verbose_name='种类图片')),
            ],
            options={
                'verbose_name': '商品种类',
                'verbose_name_plural': '商品种类',
                'db_table': 'db_goods_type',
            },
        ),
        migrations.CreateModel(
            name='IndexGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('image', models.URLField(help_text='轮播图图片', verbose_name='轮播图图片')),
                ('index', models.SmallIntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级'), (4, '第四级'), (5, '第五级'), (6, '第六级')], default=1, help_text='轮播图优先级', verbose_name='轮播图优先级')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'db_table': 'db_index_goods_banner',
            },
        ),
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='活动名称', max_length=20, verbose_name='活动名称')),
                ('image', models.URLField(help_text='首页促销活动图片', verbose_name='首页促销活动图片')),
                ('url', models.URLField(help_text='首页促销活动链接', verbose_name='首页促销活动链接')),
                ('index', models.SmallIntegerField(help_text='首页促销活动图片优先级', verbose_name='首页促销活动图片优先级')),
            ],
            options={
                'verbose_name': '首页促销活动',
                'verbose_name_plural': '首页促销活动',
                'db_table': 'db_index_promotion_banner',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('display_type', models.SmallIntegerField(choices=[(0, '文字'), (1, '图片')], default=0, help_text='展示类型', verbose_name='展示类型')),
                ('index', models.SmallIntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级'), (4, '第四级'), (5, '第五级'), (6, '第六级')], default=1, help_text='轮播图优先级', verbose_name='轮播图优先级')),
                ('goodstype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU')),
            ],
            options={
                'verbose_name': '首页分类商品',
                'verbose_name_plural': '首页分类商品',
                'db_table': 'db_index_type_goods_banner',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='商品种类'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU'),
        ),
    ]
