# Generated by Django 2.1.4 on 2020-01-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('count', models.IntegerField(default=1, help_text='商品数量', verbose_name='商品数量')),
                ('price', models.FloatField(help_text='商品价格', verbose_name='商品价格')),
                ('comment', models.CharField(max_length=250, verbose_name='评论')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'db_order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_date', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('order_id', models.IntegerField(help_text='订单id', primary_key=True, serialize=False, verbose_name='订单id')),
                ('pay_meihod', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '微信支付'), (3, '支付宝'), (4, '银联支付')], default=3, help_text='支付方式', verbose_name='支付方式')),
                ('total_count', models.IntegerField(default=1, help_text='商品数量', verbose_name='商品数量')),
                ('total_price', models.FloatField(help_text='支付金额', verbose_name='支付金额')),
                ('transit_price', models.FloatField(help_text='运费', verbose_name='运费')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评论'), (5, '已完成')], default=1, help_text='支付状态', verbose_name='支付状态')),
                ('trade_no', models.CharField(help_text='支付编码', max_length=120, verbose_name='支付编码')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'db_order_info',
            },
        ),
    ]
